+++
date = "2015-05-23T22:18:00.001-07:00"
title = "Book Review: Close Up at a Distance"
tags = ['goals', 'GSAPP', 'satellites', 'GIS', 'book review', 'GPS']
+++
Although [Laura Kurgan](http://www.arch.columbia.edu/about/people/ljk33columbiaedu) was not directly one of my studio critics at GSAPP, I was able to work with her somewhat as part of the C-BIP Studio, where she, David Benjamin, and my assigned critic Scott Marble teamed up to co-teach a joint studio on parametric design and building systems.  I appreciated Laura as an attentive and careful critic, but I didn't get to learn much about her own work until reading her book, *[Close Up at a Distance: Mapping, Technology and Politics](http://www.amazon.com/Close-Up-Distance-Technology-Politics/dp/1935408283/)* (2013).  I attended a lecture that she gave introducing the book in 2013, then finally got around to reading it this past year.

<img src="http://4.bp.blogspot.com/-ksL4auKhvwU/VWFeIiRg_pI/AAAAAAAAF4c/waL69GdCYvk/s1600/IMG_20150523_221151.jpg"/>

As the title of the book suggests, Laura's work focuses on mapping, especially on satellite and surveillance imagery as used in mapping, which allows for a "close up" image of the world taken "at a distance."  I thought her lecture was extremely interesting, which was the reason I bought and read the book.  Her work tries to deconstruct the process of satellite imagery to explore its origins and reveal its biases.  I took some notes on her lecture that I've copied here:

"The weight of objectivity now falls on the satellite view instead of on the photograph.  The photograph is now understood as a subjective view, but the satellite image is seen as objective, unbiased, although realistically it is even more mediated than the photograph.  An open question is whether the satellite image is in some way "tainted" by the military origins of the technology required to produce it.  This confusion underscores the importance of visual literacy, of knowing how images are produced and presented.  There is an art to the analysis of satellite images.  [LANDSAT](http://en.wikipedia.org/wiki/Landsat_program) is both civilian and military at the same time.  There are 24 satellites orbiting Earth, and four of them are needed for a precise location with [GPS](http://en.wikipedia.org/wiki/Global_Positioning_System).  Problems arise when the satellite data is dissociated from the image."

The book is essentially an essay describing Laura's practices and concerns, followed by descriptions of nine projects (installations, exhibitions, research projects) that she carried out on these themes over the last twenty-or-so years.  The projects are represented as they were presented originally, together with some retrospective commentary added to describe the further life and meaning of the projects.  If you have never thought about GPS technology before, or the fact that multiple spacecraft flying by overhead are needed for some of the most mundane features of your life (getting directions, figuring out where you are), then this is an important book for you.  Considering that GPS technology has become ubiquitous since 1990, and satellite views are now just as common as road maps, I think it's important for those of us with an interest in how things work - by which I mean who controls and directs our access to information - to understand this technology.  My [GIS ](http://en.wikipedia.org/wiki/Geographic_information_system)professor, Leah Meisterlin, loved to say "maps [can] lie," but Laura shows that maps and satellite imagery can also be powerful tools for truth when their content is sufficiently repurposed, recontextualized, interrogated, or re-presented for ethical, activist, and memorial reasons, to paraphrase a line from the book (57).

<img src="http://4.bp.blogspot.com/-eM3cftkWSkI/VWFeLdRnBkI/AAAAAAAAF4k/LLo_buUS8Fk/s1600/IMG_20150523_221210.jpg"/>

Beyond the interesting content of the book, and its lovely graphic design, I found *Close Up at a Distance* to be inspiring because of the way it treats architectural practice.  In projects like the ones it describes, I think I can see a way forward for my own architecture work outside the office.  Beyond the flashy architecture competitions that inevitably end in time wasted, no feedback, and empty images, there are design problems to be solved with real meaning for social and environmental justice - I just need to tackle some of them.  I have adopted a goal of completing ten projects in ten years, since one project per year shouldn't be too much of a stretch.  A project could be a competition entry, an essay, a photo series, or an artwork, but each project must have a visual component.  I'm starting this year, so in 2025, I should be able to look back on time well spent.  I don't expect to have anything worth publishing or exhibiting at the end, but if I do, that would be all the better.  The point is to keep trying new things, keep learning, keep seeking out places and problems that could benefit from visual literacy and a design approach, and not to get lost in the minutiae of waterproofing details and occupancy calculations.  I don't want to lose the real joy of research and discovery that I experienced with each new semester at GSAPP, and Laura's book has helped me find a way to do that.  For that, it has earned a place on my shelf.

Recommended.
