+++
date = "2012-06-12T19:18:00.000-07:00"
title = "Israel/Palestine: Day 6"
tags = []
+++
Thursday, May 24th

After a very long day of meeting with organizations around Bethlehem, it was time to say goodbye to the city and continue on to our next destination.  Unfortunately around this time I got sick, probably from not getting enough sleep, and the cold I caught followed me for the rest of the trip.  (Special thanks to Suzanne for providing me with cold medicine, since I didn't pack any!)  On the 24th, we got up extra early so we could take the time to walk through the Bethlehem checkpoint to experience what ordinary Palestinians encounter when they venture into Israel.  Despite our early start we arrived after the morning rush, so the lines were empty and we went through rather quickly.  To get from Bethlehem to Jerusalem, which are about seven minutes apart by car if you can go straight, residents of the West Bank must first apply for a permit that will allow them into Jerusalem on a given day between the hours of 7am and 7pm (or starting at 5am if you have a work permit).  Since you must have an Israeli license plate (blue and yellow) to drive out of the West Bank, and Palestinians only have Palestinian license plates (green and white), most people have to walk through the checkpoint and take a taxi to their destination.  Since I didn't take any pictures, you'll have to imagine what it's like inside (and see photos of the outside [here](http://972mag.com/bethlehem17712/17712/)).  The checkpoint is composed of a series of ramps, turnstiles (old NYC subway-style, like rotating cages), x-ray machines/metal detectors, and booths with Israeli soldiers.  After walking through a long, fenced passage, we went through a turnstile, past a booth where a soldier checked our passports, then into a big warehouse-like building where someone we couldn't see on a loudspeaker gave us directions to put our things through an x-ray machine and walk through a metal detector.  We were confused and the loudspeaker voice seemed annoyed at our ineptitude, or maybe at the fact that we clearly didn't understand the directions given in Hebrew, but finally we were all through the metal detector, and then went to yet another booth where our passports were examined again.  Then we were through to the Jerusalem side.

Keep in mind that our usual method of travel from the West Bank into Israel is on our tour bus, in which case we do not have to do this; we simply sit on the bus, a solider comes aboard and checks that we all have our (American) passports in hand, and waves us through.  But if you aren't on a tour bus with Israeli tags, you have to go through this checkpoint on foot.  And because of the restrictions on travel, the lines in the morning can be very long ([see this video for an idea](http://www.youtube.com/watch?v=PI24DZCQwGo)).  And then you have to go back through the same way to get home before 7pm.  So a trip that used to take 7 minutes, from Bethlehem to Jerusalem, can take hours.  I think I can speak for all of us in saying that we were deeply disturbed by the experience of going through the checkpoint, but also very glad that we did, so we could see firsthand the way that Palestinians are forced to live.  (Here's [another descriptio](http://mondoweiss.net/2010/05/bethlehem-checkpoint-waiting-in-a-line-vs-waiting-in-a-line-under-occupation.html)n of what it's like to go through a checkpoint.)

After recovering our bus on the other side, we embarked for the Galilee region, where we would be spending two nights.  We drove up the Mediterranean coast and stopped at [Caesarea](http://en.wikipedia.org/wiki/Caesarea_Maritima), an ancient Roman city with some nice ruins including a circus half eroded by the incoming sea.  The city was conquered in succession by the Arabs, Crusaders, Arabs again, Ottomans, and then "rediscovered" by the British and now the Israelis.  A pretty bad video full of Sim City-like animation introduces you to the site and ends with footage of smiling happy children in ([the modern city of](http://en.wikipedia.org/wiki/Caesarea)) Caesarea.  The view of the Mediterreanean is beautiful except for the large dock and factory just south of the site...  I wish someone had thought a bit more before building that oversized industrial area just there!  Also it's an odd site since much of it was recently restored/rebuilt  and has stamps on the columns with the date, 1997.  Pretty cheesy.  The banner ads with sayings like "Caesarea Romance" and "Caesarea Magic" were also really cheesy.

<img src="http://3.bp.blogspot.com/-xDam_TvVDU8/T9f2hN9_cCI/AAAAAAAAAwY/tR42kh9wtYA/s1600/IMG_5898.jpg"/>

<img src="http://4.bp.blogspot.com/-70_Ri44Of_Q/T9f2h_plpfI/AAAAAAAAAwg/YGVCUni2ZrI/s1600/IMG_5902.jpg"/>

<img src="http://3.bp.blogspot.com/-XNAMGpURJ-o/T9f2ilCepSI/AAAAAAAAAwo/ZQlJRsXRba0/s1600/IMG_5916.jpg"/>

<img src="http://2.bp.blogspot.com/-qx-QoCwGjYI/T9f2jFeqKVI/AAAAAAAAAww/qo1PkVM65fE/s1600/IMG_5878.jpg"/>

<img src="http://2.bp.blogspot.com/-V_77mPne3ZU/T9f2nSdzTGI/AAAAAAAAAxo/Wt5oezYbDqA/s1600/IMG_5935.jpg"/>

Next stop was at [Megiddo](http://en.wikipedia.org/wiki/Tel_Megiddo), also known as [Armageddon](http://en.wikipedia.org/wiki/Armageddon).  Like many of the others on the trip I didn't realize that Armageddon is a place, and a very ancient one at that.  Unfortunately the site itself is really boring - not much has survived from its 26 different civilizations, all of whom fortified and occupied this hill in the middle of a valley to protect the valley and its trade routes.  It's basically a really big pile of human trash; there was no hill there originally.  After wandering over the hill for a bit we went down to the underground spring that supplied the tell with water once upon a time, although there's no water there now since it's all been diverted.

<img src="http://1.bp.blogspot.com/-QsviEwFPC7s/T9f2j8nbusI/AAAAAAAAAw4/hdlbBIMLfeY/s1600/IMG_5956.jpg"/>

<img src="http://3.bp.blogspot.com/-IXAC6WgGv_A/T9f2kgr4D6I/AAAAAAAAAxA/QeQCMcpyEAM/s1600/IMG_5963.jpg"/>

<img src="http://3.bp.blogspot.com/-LmU9xMSzouc/T9f2lDK27lI/AAAAAAAAAxI/tzAjwDO9bNc/s1600/IMG_5966.jpg"/>

So off again we went and stopped in [Nazareth](http://en.wikipedia.org/wiki/Nazareth), hometown of Jesus and site of many churches dedicated to Mary and the Holy Family.  Nazareth is located in Israel, so there are no checkpoints, etc, around it like there are around Bethlehem, and people who live there are citizens of Israel.  Of course, this means that if you are a Christian Palestinian from the West Bank, it's very difficult for you to visit Nazareth, even though it's only a couple hours away from Bethlehem by car.  In Nazareth we visited a number of churches: the church of [Mary's Well](http://en.wikipedia.org/wiki/Greek_Orthodox_Church_of_the_Annunciation) (the Greek Orthodox church celebrating the Annunciation); the [Synagogue Church](http://en.wikipedia.org/wiki/Synagogue_Church), where Jesus supposedly taught in the synagogue; the Catholic [Basilica of the Annunciation](http://en.wikipedia.org/wiki/Basilica_of_the_Annunciation); and the Franciscan [church of St. Joseph](http://www.biblewalks.com/sites/StJosephChurch.html)/the Holy Family/Carpenters (possibly a carpenter's workshop, or Jesus' home, or something like that).  As usual there are two churches of the Annunciation, Greek Orthodox and Catholic, since we Christians can never agree on where things happened.  I found the Catholic version to be much more interesting, since it's a modern building with some really nice mosaics and interesting structure.  After a while all the old, not-very-well-maintained churches start to wear on you, and it's fun to see some more recent work.

<img src="http://4.bp.blogspot.com/-hcc8Wo6QRwA/T9f2m_kuVvI/AAAAAAAAAxg/oRcWSfY8l70/s1600/IMG_5977.jpg"/>

<img src="http://2.bp.blogspot.com/-0bII3pmDfQY/T9f2lxwsUTI/AAAAAAAAAxQ/vuw_mEln-8A/s1600/IMG_5983.jpg"/>

<img src="http://4.bp.blogspot.com/-u_5i8j9bo6I/T9f2mHwTvmI/AAAAAAAAAxY/mDZMAGNZ5oI/s1600/IMG_5984.jpg"/>

This was another completely full day, with a great diversity of sites - although if I had to skip one next time, I'd say leave out Megiddo (too many cows) and spend more time in Nazareth.  Caesarea felt extremely tourist-y and was interesting, but not that exciting, especially if you've seen as many Roman ruins as I have [note: see my blog posts from 2009 for non-stop Roman ruins].  That night we arrived in Tiberias, where we spent the night at the Restal Hotel.  It was the only hotel we stayed in that had a pool - but both nights I was too tired and sick to take advantage of it!  But that didn't stop me from taking part in all of our other adventures... to be continued!
